### ISSUE TITLE
Gruvbox dunst

### ISSUE THREAD

**Issue by Spuxy** [b4skyx/dotfiles#1]
Hey Mate, first of all i would like to thank u for sharing ur dotfiles thanks to repo i finally made nice lookin gruvbox linux :3 !
The second thing is question about Dunst cfg if u would please provide for old gruvbox cfg :( i can not find in ur repo but its on screenshot on reddit.

**Comment by b4skyx** [comment]
I might've forgotten to take a backup of it. What you can do now is pick any other dunst config and tweak the colors to gruvbox.
