### ISSUE TITLE
searching for your old wallpaper :)

### ISSUE THREAD

**Issue by kronikpillow** [b4skyx/dotfiles#4]
I am looking for your old wallpaper from this reddit unix porn post, [[BSPWM] And the journey continues~](https://www.reddit.com/r/unixporn/comments/jzfwrx/bspwm_and_the_journey_continues/) .. I used to use it, then i accidentaly formated my backup hdd when I was switching to btrfs and lost it, meanwhile you switched the wallpaper, I found the original, but now I can't find the modified version to go with my dwm build [SS of my dwm rice](https://0x0.st/-g5a.png) :-/ do you by any chance still have it :))) 🤞🤞🤞

**Comment by b4skyx** [comment]
I am afraid I do not have the backup for that specific wallpaper. I recolored it by doing some modifications to imagegonord.
While I do not have its fork public, you can try their [website](https://ign.schrodinger-hat.it/) to get a similar effect.
