### ISSUE TITLE
Where did you get your icons

### ISSUE THREAD

**Issue by keven-mate** [b4skyx/dotfiles#5]
I've searched all over the web, but I can't find any cheatsheet that has the icons you used, can you send me the link of where you got them?

**Comment by Spuxy** [comment]
which icons ? U mean gtk icons ? Flattery/ Papirus
If u do not see icons at polybar so u need to compile/download sinji font?
Or if u are worry about terminal i recommend to download Nerd fonts

**Comment by keven-mate** [comment]
Polybar's icons, I already have siji installed, I just needed to know where he got the icons from, for his polybar.

**Comment by b4skyx** [comment]
For polybar I use siji/waffle.
You can extract icons via gucharmap. Select private use area in unicode block. All the available fontset icons will be visible. You can copy paste the font or unicode from there itself.

**Comment by keven-mate** [comment]
Thanks a lot, I will test it today when I'm free.

**Comment by keven-mate** [comment]
Some icons are not showing up, how can I fix it?

**Comment by Spuxy** [comment]
Icons at polybar? Does not show up?

**Comment by keven-mate** [comment]
Yes, some icons don't show on Polybar, others have don't show on Gucharmap.

I'm more worried with the ones that don't show on Polybar, and @b4skyx you said you're using waffle font, how can I use it?

**Comment by b4skyx** [comment]
> Yes, some icons don't show on Polybar, others have don't show on Gucharmap.
> 
> I'm more worried with the ones that don't show on Polybar, and @b4skyx you said you're using waffle font, how can I use it?

The one available in this repo should have all the icons use. Waffle is just a fine tuned version of Siji. You can use siji instead. If the font doesn't shows in gucharmap you can try converting it to ttf.
